### PR TITLE
$watch should return unwatch function

### PR DESCRIPTION
**Pull request by alsotang**
https://vuex.vuejs.org/api/#watch

> To stop watching, call the returned unwatch function.

I call `$watch` in a component created, and wanna stop it when destroyed

### CODE REVIEW

**Comment by alsotang** [comment]
Now I can only use a condition var to exit the callback. But the watch is still running, not release.

**Comment by alsotang** [comment]
Wait some hours. I will write tests for this pr.

**Comment by bodograumann** [comment]
Maybe we should annotate the return type⁉

**Comment by alsotang** [comment]
yep. I will add return type

**Comment by alsotang** [comment]
ok. Tests and return type annotation are added.

**Comment by bodograumann** [comment]
Thanks for your contribution. Lgtm.

**Comment by gertqin** [comment]
Looks good! Thanks for the contribution.

**Comment by alsotang** [comment]
please publish a new version to npm. thank you

**Pull request merged**
